// models/Invoice.js
import mongoose from "mongoose";

const invoiceItemSchema = new mongoose.Schema({
  employee: {
    type: mongoose.Schema.Types.ObjectId,
    ref: "Employee",
    required: true,
  },
  employeeName: {
    type: String,
    required: true,
  },
  employeeId: {
    type: String,
    required: true,
  },
  monthlyBillingSalary: {
    type: Number,
    required: true,
    min: 0,
  },
  leaveDays: {
    type: Number,
    default: 0,
  },
  leaveDeduction: {
    type: Number,
    default: 0,
  },
  workingDays: {
    type: Number,
    default: 30, // Assuming 30 days month
  },
  actualWorkingDays: {
    type: Number,
    default: 30,
  },
  proratedAmount: {
    type: Number,
    required: true,
  },
  // Per employee TDS/GST if needed
  tdsPercent: {
    type: Number,
    default: 0,
  },
  tdsAmount: {
    type: Number,
    default: 0,
  },
  gstPercent: {
    type: Number,
    default: 0,
  },
  gstAmount: {
    type: Number,
    default: 0,
  },
  subtotal: {
    type: Number,
    required: true,
  },
});


const paymentHistorySchema = new mongoose.Schema({
  amount: {
    type: Number,
    required: true
  },
  paymentDate: {
    type: Date,
    required: true
  },
  paymentMethod: {
    type: String,
    enum: ['Cash', 'Cheque', 'Bank Transfer', 'Online', 'DD']
  },
  referenceNumber: String,
  bankName: String,
  branch: String,
  remarks: String,
  receivedBy: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'User'
  },
  recordedAt: {
    type: Date,
    default: Date.now
  }
}, { _id: true });

const invoiceSchema = new mongoose.Schema(
  {
    invoiceNumber: {
      type: String,
      required: true,
      unique: true,
    },
    school: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "School",
      required: true,
    },
    schoolDetails: {
      name: String,
      city: String,
      address: String,
      contactPersonName: String,
      mobile: String,
      email: String,
    },
    month: {
      type: Number,
      required: true,
      min: 1,
      max: 12,
    },
    year: {
      type: Number,
      required: true,
    },

    // Invoice items (employees)
    items: [invoiceItemSchema],

    // Summary
    subtotal: {
      type: Number,
      required: true,
      default: 0,
    },

    // TDS (Overall)
    tdsPercent: {
      type: Number,
      default: 0,
    },
    tdsAmount: {
      type: Number,
      default: 0,
    },

    // GST (Overall)
    gstPercent: {
      type: Number,
      default: 0,
    },
    gstAmount: {
      type: Number,
      default: 0,
    },

    // Round off
    roundOff: {
      type: Number,
      default: 0,
    },

    // Grand Total
    grandTotal: {
      type: Number,
      required: true,
    },
    previousDue: {
      type: Number,
      default: 0,
    },

    // Status
    status: {
      type: String,
      enum: ["Draft", "Generated", "Verified", "Sent", "Paid", "Cancelled"],
      default: "Generated",
    },
    paymentHistory: [paymentHistorySchema],

    verificationHistory: [
      {
        verifiedBy: {
          type: mongoose.Schema.Types.ObjectId,
          ref: "User",
        },
        verifiedAt: {
          type: Date,
          default: Date.now,
        },
        status: {
          type: String,
          enum: ["Verified", "Re-verified", "Auto-verified"],
          default: "Verified",
        },
        changes: [String],
        notes: String,
      },
    ],

    resendHistory: [
      {
        resentBy: {
          type: mongoose.Schema.Types.ObjectId,
          ref: "User",
        },
        resentAt: {
          type: Date,
          default: Date.now,
        },
        reason: String,
        previousSentAt: Date,
      },
    ],

    // Generated By System (Auto)
    generatedBy: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "User",
    },
    generatedAt: {
      type: Date,
      default: Date.now,
    },

    // Verified By Admin
    verifiedBy: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "User",
    },
    verifiedAt: Date,

    // Sent to School
    sentAt: Date,
    sentBy: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "User",
    },

    // Payment
    paymentStatus: {
      type: String,
      enum: ["Unpaid", "Partial", "Paid", "Overdue"],
      default: "Unpaid",
    },
    paidAmount: {
      type: Number,
      default: 0,
    },
    dueDate: Date,
    paidAt: Date,

    // Invoice PDF
    pdfUrl: String,
    pdfPublicId: String,

    // Customizations (Admin can modify before verification)
    customizations: {
      leaveAdjustments: [
        {
          employee: {
            type: mongoose.Schema.Types.ObjectId,
            ref: "Employee",
          },
          originalLeaveDays: Number,
          adjustedLeaveDays: Number,
          reason: String,
          adjustedBy: {
            type: mongoose.Schema.Types.ObjectId,
            ref: "User",
          },
          adjustedAt: Date,
        },
      ],
      tdsAdjustment: {
        originalPercent: Number,
        adjustedPercent: Number,
        reason: String,
      },
      gstAdjustment: {
        originalPercent: Number,
        adjustedPercent: Number,
        reason: String,
      },
      otherAdjustments: [
        {
          description: String,
          amount: Number,
          type: {
            enum: ["Add", "Deduct"],
          },
          reason: String,
        },
      ],
    },

    // Notes
    notes: String,

    createdBy: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "User",
    },
    updatedBy: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "User",
    },
  },
  {
    timestamps: true,
  },
);

invoiceSchema.pre("validate", async function (next) {
  if (this.isNew && !this.invoiceNumber) {
    const year = this.year.toString().slice(-2);
    const month = this.month.toString().padStart(2, "0");

    const lastInvoice = await this.constructor
      .findOne({
        month: this.month,
        year: this.year,
      })
      .sort({ createdAt: -1 });

    let sequence = 1;

    if (lastInvoice && lastInvoice.invoiceNumber) {
      const lastSeq = parseInt(lastInvoice.invoiceNumber.split("-")[2]);
      if (!isNaN(lastSeq)) sequence = lastSeq + 1;
    }

    this.invoiceNumber = `INV-${year}${month}-${sequence.toString().padStart(3, "0")}`;
  }

  next();
});

// Method to calculate totals
invoiceSchema.methods.calculateTotals = function () {
  // Calculate subtotal from items
  this.subtotal = this.items.reduce(
    (sum, item) => sum + item.proratedAmount,
    0,
  );

  // Calculate TDS
  this.tdsAmount = (this.subtotal * this.tdsPercent) / 100;

  // Calculate GST
  this.gstAmount = (this.subtotal * this.gstPercent) / 100;

  // Calculate grand total INCLUDING previous due
  let total =
    this.subtotal - this.tdsAmount + this.gstAmount + (this.previousDue || 0); // ⬅️ YEH CHANGE

  // Apply round off
  this.roundOff = Math.round(total) - total;
  this.grandTotal = Math.round(total);

  return {
    subtotal: this.subtotal,
    tdsAmount: this.tdsAmount,
    gstAmount: this.gstAmount,
    previousDue: this.previousDue, // ⬅️ YEH BHI ADD KARO
    roundOff: this.roundOff,
    grandTotal: this.grandTotal,
  };
};

// Virtual for days in month
invoiceSchema.virtual("daysInMonth").get(function () {
  return new Date(this.year, this.month, 0).getDate();
});

// Indexes
invoiceSchema.index({ school: 1, month: 1, year: 1 });
invoiceSchema.index({ status: 1 });
invoiceSchema.index({ invoiceNumber: 1 });
invoiceSchema.index({ paymentStatus: 1 });
invoiceSchema.index({ dueDate: 1 });

export default mongoose.model("Invoice", invoiceSchema);
